-- =============================================================================
-- 20260501000000_seed_real_sample_templates.sql
-- =============================================================================
-- Seeds production-format FSR + ILA templates into fsr_lob_templates.
--
-- Generated by ../build.mjs from the HTML files in ../html/. Do not edit
-- this file by hand; edit the HTML and re-run the builder.
--
-- Source FSR samples are in nisla-ai-pack/FSR formats/ (T-012, T-039,
-- TMT-145, 4790, EW-2794, AS-1752). The HTML templates mirror their
-- structure 1:1 with placeholders for the per-claim fillable fields.
--
-- Idempotency: each INSERT uses ON CONFLICT (company, lob, template_name,
-- version) DO NOTHING. Re-running this migration is safe and will not
-- clobber human-edited rows.
--
-- ROLLOUT NOTE — making the new templates the active default:
--   The portal's existing fsr_lob_templates already has rows for
--   (NISLA|Acuere) × (Fire | Marine Cargo) at template_name='Default'.
--   This migration adds template_name='Production' rows alongside them
--   so both coexist. To make 'Production' the active picker default,
--   you can either:
--     (a) update lib/fsr/render.js to prefer 'Production' over 'Default'
--         when both exist;
--     (b) or run the manual UPDATE statements at the bottom of this
--         file (commented out by default).
-- =============================================================================

-- Real-sample-aligned (TMT-145, 4790)
INSERT INTO public.fsr_lob_templates (company, lob, template_name, version, body_html, notes, is_active)
VALUES (
  'NISLA',
  'Marine Cargo',
  'Production',
  1,
  $body$<!DOCTYPE html>
<!--
  Marine Cargo FSR — NISLA letterhead.

  Source: derived from production FSR samples in `FSR formats/`:
    - TMT-145-25-26 (Tata Motors Passenger Vehicles, Marine STO)
    - 4790 (Grasim Industries Birla Paints, Marine Cargo Annual TO)

  Goes into the portal table `fsr_lob_templates` as:
    company='NISLA' lob='Marine Cargo' template_name='Production' version=1

  Placeholder vocabulary documented in
  `docs/CLAUDE_CODE_NOTES.md` §5. Missing placeholders render as
  the literal string "(blank)" via the portal's `lib/fsr/render.js`.

  Customisability — surveyors / managers may:
    1. Edit body_html for an existing row (small tweaks).
    2. Clone a row with a new template_name (e.g. 'New India Assurance')
       and select it at FSR-generate time.
    3. Bump version to keep history when iterating on the same name.
-->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Marine Cargo FSR — {{claim.ref_number}}</title>
  <style>
    @page { size: A4; margin: 16mm; }
    body { font-family: 'Times New Roman', Times, serif; font-size: 11pt; color: #111; line-height: 1.45; }

    .letterhead { text-align: center; border-bottom: 2px solid #1e3a5f; padding-bottom: 8px; margin-bottom: 12px; }
    .letterhead h1 { margin: 0; font-size: 14pt; color: #1e3a5f; }
    .letterhead .lob-strip { font-size: 9pt; color: #475569; margin-top: 2px; letter-spacing: 0.4px; }
    .letterhead .sub { font-size: 9pt; color: #475569; margin-top: 2px; }

    .ref-line { display: flex; justify-content: space-between; font-size: 10pt; margin: 8px 0; }
    .doc-title { text-align: center; font-size: 13pt; font-weight: 700; margin: 14px 0 4px; color: #1e3a5f; letter-spacing: 0.4px; }
    .doc-sub { text-align: center; font-size: 10pt; color: #475569; font-style: italic; margin-bottom: 12px; }

    .to-block { font-size: 10pt; margin: 12px 0; line-height: 1.45; }
    .subject { font-size: 10pt; font-weight: 700; margin: 12px 0; padding: 8px; background: #f8fafc; border-left: 3px solid #1e3a5f; }
    h2 { font-size: 11pt; color: #1e3a5f; border-bottom: 1px solid #cbd5e1; padding-bottom: 2px; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: 0.3px; }

    table.kv { width: 100%; border-collapse: collapse; margin: 6px 0 12px; }
    table.kv td { padding: 4px 6px; vertical-align: top; border: 1px solid #e2e8f0; font-size: 10pt; }
    table.kv td.lbl { width: 4%; font-weight: 600; color: #475569; text-align: center; }
    table.kv td.k   { width: 26%; font-weight: 600; color: #475569; }

    table.totals { width: 80%; margin: 12px 0 12px auto; border-collapse: collapse; font-size: 11pt; }
    table.totals td { padding: 4px 8px; }
    table.totals tr.subtotal td { font-weight: 600; border-top: 1px solid #cbd5e1; }
    table.totals tr.grand td { font-weight: 700; border-top: 2px solid #1e3a5f; padding-top: 8px; font-size: 12pt; }
    table.totals td.num { text-align: right; }

    table.loss { width: 100%; border-collapse: collapse; font-size: 9pt; margin: 8px 0; }
    table.loss th, table.loss td { border: 1px solid #cbd5e1; padding: 3px 5px; }
    table.loss th { background: #f1f5f9; font-weight: 700; text-align: center; }
    table.loss td.num { text-align: right; }

    blockquote { border-left: 3px solid #cbd5e1; margin: 8px 0; padding: 4px 12px; font-style: italic; color: #334155; background: #f8fafc; }
    ol.checklist { font-size: 10pt; margin: 4px 0 4px 18px; padding: 0; }
    ol.checklist li { margin: 2px 0; }
    .signoff { margin-top: 30px; padding-top: 12px; border-top: 1px dashed #94a3b8; }
    .footer { margin-top: 24px; font-size: 8pt; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 6px; }
    .annex { page-break-before: always; }
    p { margin: 6px 0; }
    .small { font-size: 9pt; color: #475569; }
  </style>
</head>
<body>

<!-- =========================================================== -->
<!-- 1. LETTERHEAD                                                -->
<!-- =========================================================== -->
<div class="letterhead">
  <h1>NATHANI INSURANCE SURVEYORS &amp; LOSS ASSESSORS PVT. LTD.</h1>
  <div class="lob-strip">LOP &nbsp;|&nbsp; Fire &nbsp;|&nbsp; Engineering &nbsp;|&nbsp; Misc. &nbsp;|&nbsp; Marine Cargo &nbsp;|&nbsp; Marine Hull</div>
  <div class="sub">IRDA/CORP/S.L.A. No. 200025 (Exp. 03/10/2028)</div>
  <div class="sub">Head Office: 507, Garnet Palladium, Behind Express Zone Bldg., Off WE Highway, Goregaon (E), Mumbai – 400063</div>
  <div class="sub">Mobile: 9892171640, 9890084540 &nbsp;·&nbsp; Email: pranav.kumar554@gmail.com, nathani.surveyors@gmail.com</div>
</div>

<div class="ref-line">
  <span><strong>Ref. No:</strong> {{claim.ref_number}}</span>
  <span><strong>Date:</strong> {{date_today}}</span>
</div>

<div class="doc-title">MARINE SURVEY REPORT</div>
<div class="doc-sub">(WITHOUT PREJUDICE)</div>

<!-- =========================================================== -->
<!-- 2. ADDRESSEE + SUBJECT                                       -->
<!-- =========================================================== -->
<div class="to-block">
  <strong>The Manager,</strong><br/>
  {{claim.insurer_name}}<br/>
  {{narrative.insurer_office_address}}
</div>

<div class="subject">
  <strong>Subject:</strong> Survey of consignment of LR No. {{narrative.lr_no}} dated {{narrative.lr_date}}
  (Vehicle No. {{narrative.vehicle_no}})<br/>
  <span class="small">Policy No: {{claim.policy_number}} &nbsp;||&nbsp; Insured: {{claim.insured_name}} &nbsp;||&nbsp; Claim No: {{claim.claim_number}}</span>
</div>

<!-- =========================================================== -->
<!-- 3. COVER PARAGRAPH                                           -->
<!-- =========================================================== -->
<p>Dear Sir,</p>
<p>Pursuant to valued instruction received from {{narrative.instructions_received_from}} on
   {{claim.date_of_intimation}} for survey and loss assessment of the below mentioned claim,
   we have conducted the survey as per the details below.</p>

<!-- Header summary -->
<table class="kv">
  <tr><td class="k">Instruction received from</td><td>{{narrative.instructions_received_from}}</td></tr>
  <tr><td class="k">Date of Loss</td><td>{{claim.date_loss}}</td></tr>
  <tr><td class="k">Date of Deputation</td><td>{{claim.date_of_intimation}}</td></tr>
  <tr><td class="k">Date of Survey</td><td>{{narrative.dates_of_survey}}</td></tr>
  <tr><td class="k">Place of Survey</td><td>{{narrative.place_of_survey}}</td></tr>
  <tr><td class="k">Person Contacted</td><td>{{narrative.person_contacted}}</td></tr>
  <tr><td class="k">Insured Name</td><td>{{claim.insured_name}}</td></tr>
  <tr><td class="k">LR No. / Shipment No.</td><td>{{narrative.lr_no}} dated {{narrative.lr_date}}</td></tr>
  <tr><td class="k">Location / Transit</td><td>{{narrative.transit}}</td></tr>
  <tr><td class="k">Estimated Loss Amount</td><td>{{loss_sheet.gross_loss_inr}}</td></tr>
</table>

<p>During our visit, we contacted the consignee&rsquo;s representative
   {{narrative.person_contacted}} who produced the damaged consignment for our inspection
   and described the situation of loss. Now we are submitting our final survey and loss
   assessment report which is based on the following observations and documents provided.</p>

<!-- =========================================================== -->
<!-- 4. POLICY PARTICULARS                                        -->
<!-- =========================================================== -->
<h2>1. Policy Particulars</h2>
<table class="kv">
  <tr><td class="lbl">a</td><td class="k">Insurer</td><td>{{claim.insurer_name}}</td></tr>
  <tr><td class="lbl">b</td><td class="k">Policy No.</td><td>{{claim.policy_number}}</td></tr>
  <tr><td class="lbl">c</td><td class="k">Insured</td><td>{{claim.insured_name}}</td></tr>
  <tr><td class="lbl">d</td><td class="k">Type of Policy</td><td>{{claim.lob_subcategory}}</td></tr>
  <tr><td class="lbl">e</td><td class="k">Period of Insurance</td><td>{{claim.policy_period_from}} to {{claim.policy_period_to}}</td></tr>
  <tr><td class="lbl">f</td><td class="k">Sum Insured</td><td>{{loss_sheet.sum_insured_inr}}</td></tr>
  <tr><td class="lbl">g</td><td class="k">Basis of Valuation</td><td>{{narrative.basis_of_valuation}}</td></tr>
  <tr><td class="lbl">h</td><td class="k">Packing Description</td><td>{{narrative.policy_packing_description}}</td></tr>
  <tr><td class="lbl">i</td><td class="k">Transport Mode</td><td>{{narrative.transport_mode}}</td></tr>
  <tr><td class="lbl">j</td><td class="k">Commodity Description</td><td>{{narrative.commodity_description}}</td></tr>
  <tr><td class="lbl">k</td><td class="k">Journey Details</td><td>{{narrative.journey_details}}</td></tr>
  <tr><td class="lbl">l</td><td class="k">Policy Excess</td><td>{{narrative.policy_excess_text}}</td></tr>
  <tr><td class="lbl">m</td><td class="k">Risks Covered</td><td>{{narrative.risks_covered}}</td></tr>
</table>

<!-- =========================================================== -->
<!-- 5. DETAILS OF CONSIGNMENT                                    -->
<!-- =========================================================== -->
<h2>2. Details of Consignment</h2>
<table class="kv">
  <tr><td class="lbl">a</td><td class="k">Carrier</td><td>{{narrative.carrier}}</td></tr>
  <tr><td class="lbl">b</td><td class="k">Consignor</td><td>{{narrative.consignor}}</td></tr>
  <tr><td class="lbl">c</td><td class="k">Consignee</td><td>{{narrative.consignee}}</td></tr>
  <tr><td class="lbl">d</td><td class="k">LR No. / Shipment No.</td><td>{{narrative.lr_no}} dated {{narrative.lr_date}}</td></tr>
  <tr><td class="lbl">e</td><td class="k">Description of Goods</td><td>{{narrative.goods_description}}</td></tr>
  <tr><td class="lbl">f</td><td class="k">Transit</td><td>{{narrative.transit}}</td></tr>
  <tr><td class="lbl">g</td><td class="k">Invoice Details</td><td>{{narrative.invoice_details}}</td></tr>
  <tr><td class="lbl">h</td><td class="k">Vehicle No.</td><td>{{narrative.vehicle_no}}</td></tr>
  <tr><td class="lbl">i</td><td class="k">Total Consignment Value</td><td>{{narrative.total_consignment_value_inr}}</td></tr>
</table>

<!-- =========================================================== -->
<!-- 6. PACKING DESCRIPTION                                       -->
<!-- =========================================================== -->
<h2>3. Packing Description</h2>
<p>{{narrative.packing_description}}</p>

<!-- =========================================================== -->
<!-- 7. SEQUENCE OF INCIDENT                                      -->
<!-- =========================================================== -->
<h2>4. Sequence of Incident</h2>
<table class="kv">
  <tr><td class="lbl">a</td><td class="k">Date of Booking</td><td>{{narrative.date_of_booking}}</td></tr>
  <tr><td class="lbl">b</td><td class="k">Date of Arrival / Unloading</td><td>{{narrative.date_of_arrival}}</td></tr>
</table>

<!-- =========================================================== -->
<!-- 8. SITUATION OF LOSS                                         -->
<!-- =========================================================== -->
<h2>5. Situation of Loss</h2>
<p>{{narrative.situation_of_loss}}</p>

<!-- =========================================================== -->
<!-- 9. OUR OBSERVATIONS / FINDINGS / SURVEY                      -->
<!-- =========================================================== -->
<h2>6. Our Observations / Findings / Survey</h2>
<p>{{narrative.observations}}</p>

<!-- =========================================================== -->
<!-- 10. CAUSE OF LOSS                                            -->
<!-- =========================================================== -->
<h2>7. Cause of Loss</h2>
<p>{{ila.preliminary_view}}</p>

<!-- =========================================================== -->
<!-- 11. INSURED'S CLAIM                                          -->
<!-- =========================================================== -->
<h2>8. Insured&rsquo;s Claim</h2>
<p>The insured has claimed a loss of <strong>{{narrative.insured_claim_amount_inr}}</strong>
   ({{narrative.insured_claim_amount_words}}).</p>

<!-- =========================================================== -->
<!-- 12. ASSESSMENT OF LOSS                                       -->
<!-- =========================================================== -->
<h2>9. Assessment of Loss</h2>
<p>The loss has been assessed on the following basis:</p>
<ul class="small">
  <li>The damaged items were verified by us during the course of survey and considered accordingly as described in the report.</li>
  <li>The rates have been considered as per documents (invoices) provided by the insured / consignee.</li>
  <li>{{narrative.gst_treatment}}</li>
  <li>Basis of Valuation: {{narrative.basis_of_valuation}}</li>
  <li>Salvage: {{narrative.salvage_basis}}</li>
  <li>Excess: {{narrative.policy_excess_text}}</li>
</ul>

<table class="totals">
  <tr><td>Subtotal (damaged-qty × rate)</td><td class="num">{{loss_sheet.subtotal_inr}}</td></tr>
  <tr class="subtotal"><td>Add: Insurance @ {{loss_sheet.insurance_rate_pct}}%</td><td class="num">{{loss_sheet.insurance_total_inr}}</td></tr>
  <tr><td>Pre-GST Total</td><td class="num">{{loss_sheet.pre_gst_inr}}</td></tr>
  <tr class="subtotal"><td>Add: GST @ {{loss_sheet.gst_rate_pct}}%</td><td class="num">{{loss_sheet.gst_amount_inr}}</td></tr>
  <tr><td>Sub-Total (after GST)</td><td class="num">{{loss_sheet.after_gst_inr}}</td></tr>
  <tr class="subtotal"><td>Add: {{loss_sheet.handling_label}} @ {{loss_sheet.handling_rate_pct}}%</td><td class="num">{{loss_sheet.handling_amount_inr}}</td></tr>
  <tr><td>Gross Assessed Loss</td><td class="num">{{loss_sheet.gross_loss_inr}}</td></tr>
  <tr class="subtotal"><td>Less: Salvage</td><td class="num">{{loss_sheet.salvage_inr}}</td></tr>
  <tr><td>Net Assessed Loss</td><td class="num">{{loss_sheet.net_loss_inr}}</td></tr>
  <tr class="subtotal"><td>Less: Policy Excess</td><td class="num">{{loss_sheet.excess_inr}}</td></tr>
  <tr class="grand"><td>Net Adjusted Loss</td><td class="num">{{loss_sheet.net_adjusted_loss_inr}}</td></tr>
</table>

<p>(<strong>{{loss_sheet.net_adjusted_loss_words}}</strong>) subject to policy terms,
   conditions and final approval by the insurer.</p>

<!-- =========================================================== -->
<!-- 13. ADMISSIBILITY OF CLAIM                                   -->
<!-- =========================================================== -->
<h2>10. Admissibility of Claim</h2>
<p>Based on the facts of the case, documents examined, and observations made during
   the survey, we are of the opinion that the reported loss is
   <strong>{{ila.admissibility_label}}</strong> under the policy, subject to terms,
   conditions, warranties and exclusions.</p>
<p>{{ila.admissibility_reasoning}}</p>

<!-- =========================================================== -->
<!-- 14. CONSENT OF THE INSURED                                   -->
<!-- =========================================================== -->
<h2>11. Consent of the Insured</h2>
<p>{{narrative.consent_of_insured}}</p>

<!-- =========================================================== -->
<!-- 15. RECOMMENDATION                                           -->
<!-- =========================================================== -->
<h2>12. Recommendation</h2>
<p>We hereby recommend to the insurers to kindly settle this claim by paying
   <strong>{{loss_sheet.net_adjusted_loss_inr}}</strong>
   ({{loss_sheet.net_adjusted_loss_words}}) to the insured.</p>

<!-- =========================================================== -->
<!-- 16. RECOVERY RIGHTS (optional — kept for insurers that need it) -->
<!-- =========================================================== -->
<h2>13. Recovery Rights</h2>
<table class="kv">
  <tr><td class="k">Any remarks on LR</td><td>{{narrative.lr_remarks}}</td></tr>
  <tr><td class="k">Damage certificate obtained from carrier</td><td>{{narrative.damage_certificate}}</td></tr>
  <tr><td class="k">Monetary claim lodged on carrier (Regd. A/D)</td><td>{{narrative.monetary_claim_status}}</td></tr>
  <tr><td class="k">Probable cause of damage</td><td>{{narrative.probable_cause}}</td></tr>
</table>

<!-- =========================================================== -->
<!-- 17. NOTES + DECLARATION                                      -->
<!-- =========================================================== -->
<h2>14. Notes</h2>
<ol class="checklist">
  <li>No breach of warranty was observed during the course of survey.</li>
  <li>The loss falls within the policy period.</li>
  <li>The subject matter is covered under the policy.</li>
  <li>The loss has been caused by an insured peril.</li>
</ol>

<h2>15. Declaration</h2>
<p>We hereby declare that we have no interest in the subject matter in question and
   reported on as above. We are neither related to the insured nor the business —
   either by blood, business or shareholding of whatsoever nature.</p>

<!-- =========================================================== -->
<!-- 18. CLOSING + SIGNOFF                                        -->
<!-- =========================================================== -->
<p>This concludes our final survey and loss assessment report which is issued without
   prejudice and is subject to the terms and conditions of the policy of insurance issued
   to and held by the insured, reserving our rights to alter / amend unintended error,
   if any.</p>

<p class="small"><em>(For discretion of insurer &amp; their legal advisers only)</em></p>

<div class="signoff">
  <p style="margin-top: 22px;">
    <strong>Authorized Signatory</strong><br/>
    <strong>{{signer.name}}</strong> (Surveyor)<br/>
    IRDAI Licence: {{signer.license}}<br/>
    For Nathani Insurance Surveyors and Loss Assessors Pvt. Ltd.<br/>
    <span class="small">Date: {{date_today}}</span>
  </p>
</div>

<div class="footer">
  Generated by NISLA Portal &nbsp;·&nbsp; Surveyor reference {{claim.ref_number}}
</div>

<!-- =========================================================== -->
<!-- ANNEXURE A — itemised damage table                            -->
<!-- =========================================================== -->
<div class="annex">
  <h2 style="margin-top: 0;">Annexure-A — Itemised Cargo Damage</h2>
  {{loss_items_table}}
  <p class="small" style="margin-top: 14px;">
    All amounts in INR. Quantities reflect the consignor&rsquo;s commercial invoice and
    were verified during the course of survey.
  </p>
</div>

</body>
</html>
$body$,
  'Real-sample-aligned (TMT-145, 4790)',
  true
)
ON CONFLICT (company, lob, template_name, version) DO NOTHING;

-- Real-sample-aligned (T-012, T-039)
INSERT INTO public.fsr_lob_templates (company, lob, template_name, version, body_html, notes, is_active)
VALUES (
  'Acuere',
  'Marine Cargo',
  'Production',
  1,
  $body$<!DOCTYPE html>
<!--
  Marine Cargo FSR — ACUERE letterhead.

  Source: derived from production FSR samples in `FSR formats/`:
    - T-012-26-27 (Simero Vitrified Pvt Ltd, Marine Cargo Open Policy)
    - T-039-26-27 (Qutone Ceramic, Marine Cargo Annual Turnover Policy)

  Goes into the portal table `fsr_lob_templates` as:
    company='Acuere' lob='Marine Cargo' template_name='Production' version=1

  Structurally identical to marine-cargo--nisla.html — only the letterhead,
  IRDAI license string, and accent colour differ. This mirrors how the
  two firms operate the same workflow under different licences.
-->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Marine Cargo FSR — {{claim.ref_number}}</title>
  <style>
    @page { size: A4; margin: 16mm; }
    body { font-family: 'Times New Roman', Times, serif; font-size: 11pt; color: #111; line-height: 1.45; }

    .letterhead { text-align: center; border-bottom: 2px solid #1a7ab5; padding-bottom: 8px; margin-bottom: 12px; }
    .letterhead h1 { margin: 0; font-size: 14pt; color: #1a7ab5; }
    .letterhead .lob-strip { font-size: 9pt; color: #475569; margin-top: 2px; letter-spacing: 0.4px; }
    .letterhead .sub { font-size: 9pt; color: #475569; margin-top: 2px; }

    .ref-line { display: flex; justify-content: space-between; font-size: 10pt; margin: 8px 0; }
    .doc-title { text-align: center; font-size: 13pt; font-weight: 700; margin: 14px 0 4px; color: #1a7ab5; letter-spacing: 0.4px; }
    .doc-sub { text-align: center; font-size: 10pt; color: #475569; font-style: italic; margin-bottom: 12px; }

    .to-block { font-size: 10pt; margin: 12px 0; line-height: 1.45; }
    .subject { font-size: 10pt; font-weight: 700; margin: 12px 0; padding: 8px; background: #f0f9ff; border-left: 3px solid #1a7ab5; }
    h2 { font-size: 11pt; color: #1a7ab5; border-bottom: 1px solid #cbd5e1; padding-bottom: 2px; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: 0.3px; }

    table.kv { width: 100%; border-collapse: collapse; margin: 6px 0 12px; }
    table.kv td { padding: 4px 6px; vertical-align: top; border: 1px solid #e2e8f0; font-size: 10pt; }
    table.kv td.lbl { width: 4%; font-weight: 600; color: #475569; text-align: center; }
    table.kv td.k   { width: 26%; font-weight: 600; color: #475569; }

    table.totals { width: 80%; margin: 12px 0 12px auto; border-collapse: collapse; font-size: 11pt; }
    table.totals td { padding: 4px 8px; }
    table.totals tr.subtotal td { font-weight: 600; border-top: 1px solid #cbd5e1; }
    table.totals tr.grand td { font-weight: 700; border-top: 2px solid #1a7ab5; padding-top: 8px; font-size: 12pt; }
    table.totals td.num { text-align: right; }

    table.loss { width: 100%; border-collapse: collapse; font-size: 9pt; margin: 8px 0; }
    table.loss th, table.loss td { border: 1px solid #cbd5e1; padding: 3px 5px; }
    table.loss th { background: #f1f5f9; font-weight: 700; text-align: center; }
    table.loss td.num { text-align: right; }

    blockquote { border-left: 3px solid #cbd5e1; margin: 8px 0; padding: 4px 12px; font-style: italic; color: #334155; background: #f0f9ff; }
    ol.checklist { font-size: 10pt; margin: 4px 0 4px 18px; padding: 0; }
    ol.checklist li { margin: 2px 0; }
    .signoff { margin-top: 30px; padding-top: 12px; border-top: 1px dashed #94a3b8; }
    .footer { margin-top: 24px; font-size: 8pt; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 6px; }
    .annex { page-break-before: always; }
    p { margin: 6px 0; }
    .small { font-size: 9pt; color: #475569; }
  </style>
</head>
<body>

<div class="letterhead">
  <h1>ACUERE SURVEYORS</h1>
  <div class="lob-strip">Fire &nbsp;|&nbsp; Misc &nbsp;|&nbsp; Engg. &nbsp;|&nbsp; Marine Cargo &nbsp;|&nbsp; Motor</div>
  <div class="sub">IRDAI Licence: IRDAI/IND/SLA-85225 (Exp. 02/03/2028)</div>
  <div class="sub">A-45, 401, Gurukrupa, Gokuldham, Goregaon (E), Mumbai – 400063</div>
  <div class="sub">Contact: 9892976754, 9892596754 &nbsp;·&nbsp; Office: 022-28741640 &nbsp;·&nbsp; Email: niteennathani@gmail.com, acueresurveyors@gmail.com</div>
</div>

<div class="ref-line">
  <span><strong>Ref. No:</strong> {{claim.ref_number}}</span>
  <span><strong>Date:</strong> {{date_today}}</span>
</div>

<div class="doc-title">MARINE SURVEY REPORT</div>
<div class="doc-sub">(WITHOUT PREJUDICE)</div>

<div class="to-block">
  <strong>The Manager,</strong><br/>
  {{claim.insurer_name}}<br/>
  {{narrative.insurer_office_address}}
</div>

<div class="subject">
  <strong>Subject:</strong> Survey of consignment of LR No. {{narrative.lr_no}} dated {{narrative.lr_date}}
  (Vehicle No. {{narrative.vehicle_no}})<br/>
  <span class="small">Policy No: {{claim.policy_number}} &nbsp;||&nbsp; Insured: {{claim.insured_name}} &nbsp;||&nbsp; Claim No: {{claim.claim_number}}</span>
</div>

<p>Dear Sir,</p>
<p>Pursuant to valued instruction received from {{narrative.instructions_received_from}} on
   {{claim.date_of_intimation}} for survey and loss assessment of the below mentioned claim,
   we have conducted the survey as per the details below.</p>

<table class="kv">
  <tr><td class="k">Instruction received from</td><td>{{narrative.instructions_received_from}}</td></tr>
  <tr><td class="k">Date of Loss</td><td>{{claim.date_loss}}</td></tr>
  <tr><td class="k">Date of Deputation</td><td>{{claim.date_of_intimation}}</td></tr>
  <tr><td class="k">Date of Survey</td><td>{{narrative.dates_of_survey}}</td></tr>
  <tr><td class="k">Place of Survey</td><td>{{narrative.place_of_survey}}</td></tr>
  <tr><td class="k">Person Contacted</td><td>{{narrative.person_contacted}}</td></tr>
  <tr><td class="k">Insured Name</td><td>{{claim.insured_name}}</td></tr>
  <tr><td class="k">LR No. / Shipment No.</td><td>{{narrative.lr_no}} dated {{narrative.lr_date}}</td></tr>
  <tr><td class="k">Location / Transit</td><td>{{narrative.transit}}</td></tr>
  <tr><td class="k">Estimated Loss Amount</td><td>{{loss_sheet.gross_loss_inr}}</td></tr>
</table>

<p>During our visit, we contacted the consignee&rsquo;s representative
   {{narrative.person_contacted}} who produced the damaged consignment for our inspection
   and described the situation of loss. Photographs of the damaged consignment were snapped
   from different angles bespeaking the damages. Now we are submitting our final survey and
   loss assessment report which is based on the following observations and documents
   provided.</p>

<h2>1. Policy Particulars</h2>
<table class="kv">
  <tr><td class="lbl">a</td><td class="k">Insurer</td><td>{{claim.insurer_name}}</td></tr>
  <tr><td class="lbl">b</td><td class="k">Policy No.</td><td>{{claim.policy_number}}</td></tr>
  <tr><td class="lbl">c</td><td class="k">Insured</td><td>{{claim.insured_name}}</td></tr>
  <tr><td class="lbl">d</td><td class="k">Type of Policy</td><td>{{claim.lob_subcategory}}</td></tr>
  <tr><td class="lbl">e</td><td class="k">Period of Insurance</td><td>{{claim.policy_period_from}} to {{claim.policy_period_to}}</td></tr>
  <tr><td class="lbl">f</td><td class="k">Sum Insured</td><td>{{loss_sheet.sum_insured_inr}}</td></tr>
  <tr><td class="lbl">g</td><td class="k">Basis of Valuation</td><td>{{narrative.basis_of_valuation}}</td></tr>
  <tr><td class="lbl">h</td><td class="k">Packing Description</td><td>{{narrative.policy_packing_description}}</td></tr>
  <tr><td class="lbl">i</td><td class="k">Transport Mode</td><td>{{narrative.transport_mode}}</td></tr>
  <tr><td class="lbl">j</td><td class="k">Commodity Description</td><td>{{narrative.commodity_description}}</td></tr>
  <tr><td class="lbl">k</td><td class="k">Journey Details</td><td>{{narrative.journey_details}}</td></tr>
  <tr><td class="lbl">l</td><td class="k">Policy Excess</td><td>{{narrative.policy_excess_text}}</td></tr>
  <tr><td class="lbl">m</td><td class="k">Risks Covered</td><td>{{narrative.risks_covered}}</td></tr>
</table>

<h2>2. Details of Consignment</h2>
<table class="kv">
  <tr><td class="lbl">a</td><td class="k">Carrier</td><td>{{narrative.carrier}}</td></tr>
  <tr><td class="lbl">b</td><td class="k">Consignor</td><td>{{narrative.consignor}}</td></tr>
  <tr><td class="lbl">c</td><td class="k">Consignee</td><td>{{narrative.consignee}}</td></tr>
  <tr><td class="lbl">d</td><td class="k">LR No. / Shipment No.</td><td>{{narrative.lr_no}} dated {{narrative.lr_date}}</td></tr>
  <tr><td class="lbl">e</td><td class="k">Description of Goods</td><td>{{narrative.goods_description}}</td></tr>
  <tr><td class="lbl">f</td><td class="k">Transit</td><td>{{narrative.transit}}</td></tr>
  <tr><td class="lbl">g</td><td class="k">Invoice Details</td><td>{{narrative.invoice_details}}</td></tr>
  <tr><td class="lbl">h</td><td class="k">Vehicle No.</td><td>{{narrative.vehicle_no}}</td></tr>
  <tr><td class="lbl">i</td><td class="k">Total Consignment Value</td><td>{{narrative.total_consignment_value_inr}}</td></tr>
</table>

<h2>3. Packing Description</h2>
<p>{{narrative.packing_description}}</p>

<h2>4. Sequence of Incident</h2>
<table class="kv">
  <tr><td class="lbl">a</td><td class="k">Date of Booking</td><td>{{narrative.date_of_booking}}</td></tr>
  <tr><td class="lbl">b</td><td class="k">Date of Arrival / Unloading</td><td>{{narrative.date_of_arrival}}</td></tr>
</table>

<h2>5. Situation of Loss</h2>
<p>{{narrative.situation_of_loss}}</p>

<h2>6. Our Observations / Findings / Survey</h2>
<p>{{narrative.observations}}</p>

<h2>7. Cause of Loss</h2>
<p>{{ila.preliminary_view}}</p>

<h2>8. Insured&rsquo;s Claim</h2>
<p>The insured has claimed a loss of <strong>{{narrative.insured_claim_amount_inr}}</strong>
   ({{narrative.insured_claim_amount_words}}).</p>

<h2>9. Assessment of Loss</h2>
<p>The loss has been assessed on the following basis:</p>
<ul class="small">
  <li>The damaged items were verified by us during the course of survey and considered accordingly.</li>
  <li>The rates have been considered as per documents (invoices) provided by the insured / consignee.</li>
  <li>{{narrative.gst_treatment}}</li>
  <li>Basis of Valuation: {{narrative.basis_of_valuation}}</li>
  <li>Salvage: {{narrative.salvage_basis}}</li>
  <li>Excess: {{narrative.policy_excess_text}}</li>
</ul>

<table class="totals">
  <tr><td>Subtotal (damaged-qty × rate)</td><td class="num">{{loss_sheet.subtotal_inr}}</td></tr>
  <tr class="subtotal"><td>Add: Insurance @ {{loss_sheet.insurance_rate_pct}}%</td><td class="num">{{loss_sheet.insurance_total_inr}}</td></tr>
  <tr><td>Pre-GST Total</td><td class="num">{{loss_sheet.pre_gst_inr}}</td></tr>
  <tr class="subtotal"><td>Add: GST @ {{loss_sheet.gst_rate_pct}}%</td><td class="num">{{loss_sheet.gst_amount_inr}}</td></tr>
  <tr><td>Sub-Total (after GST)</td><td class="num">{{loss_sheet.after_gst_inr}}</td></tr>
  <tr class="subtotal"><td>Add: {{loss_sheet.handling_label}} @ {{loss_sheet.handling_rate_pct}}%</td><td class="num">{{loss_sheet.handling_amount_inr}}</td></tr>
  <tr><td>Gross Assessed Loss</td><td class="num">{{loss_sheet.gross_loss_inr}}</td></tr>
  <tr class="subtotal"><td>Less: Salvage</td><td class="num">{{loss_sheet.salvage_inr}}</td></tr>
  <tr><td>Net Assessed Loss</td><td class="num">{{loss_sheet.net_loss_inr}}</td></tr>
  <tr class="subtotal"><td>Less: Policy Excess</td><td class="num">{{loss_sheet.excess_inr}}</td></tr>
  <tr class="grand"><td>Net Adjusted Loss</td><td class="num">{{loss_sheet.net_adjusted_loss_inr}}</td></tr>
</table>

<p>(<strong>{{loss_sheet.net_adjusted_loss_words}}</strong>) subject to policy terms,
   conditions and final approval by the insurer.</p>

<h2>10. Admissibility of Claim</h2>
<p>Based on the facts of the case, documents examined, and observations made during
   the survey, we are of the opinion that the reported loss is
   <strong>{{ila.admissibility_label}}</strong> under the policy, subject to terms,
   conditions, warranties and exclusions.</p>
<p>{{ila.admissibility_reasoning}}</p>

<h2>11. Consent of the Insured</h2>
<p>{{narrative.consent_of_insured}}</p>

<h2>12. Recommendation</h2>
<p>We hereby recommend to the insurers to kindly settle this claim by paying
   <strong>{{loss_sheet.net_adjusted_loss_inr}}</strong>
   ({{loss_sheet.net_adjusted_loss_words}}) to the insured.</p>

<h2>13. Recovery Rights</h2>
<table class="kv">
  <tr><td class="k">Any remarks on LR</td><td>{{narrative.lr_remarks}}</td></tr>
  <tr><td class="k">Damage certificate obtained from carrier</td><td>{{narrative.damage_certificate}}</td></tr>
  <tr><td class="k">Monetary claim lodged on carrier (Regd. A/D)</td><td>{{narrative.monetary_claim_status}}</td></tr>
  <tr><td class="k">Probable cause of damage</td><td>{{narrative.probable_cause}}</td></tr>
</table>

<h2>14. Notes</h2>
<ol class="checklist">
  <li>No breach of warranty was observed during the course of survey.</li>
  <li>The loss falls within the policy period.</li>
  <li>The subject matter is covered under the policy.</li>
  <li>The loss has been caused by an insured peril.</li>
</ol>

<h2>15. Declaration</h2>
<p>We hereby declare that we have no interest in the subject matter in question and
   reported on as above. We are neither related to the insured nor the business —
   either by blood, business or shareholding of whatsoever nature.</p>

<p>This concludes our final survey and loss assessment report which is issued without
   prejudice and is subject to the terms and conditions of the policy of insurance issued
   to and held by the insured, reserving our rights to alter / amend unintended error,
   if any.</p>

<p class="small"><em>(For discretion of insurer &amp; their legal advisers only)</em></p>

<div class="signoff">
  <p style="margin-top: 22px;">
    <strong>Authorized Signatory</strong><br/>
    <strong>{{signer.name}}</strong> (Surveyor)<br/>
    IRDAI Licence: {{signer.license}}<br/>
    For Acuere Surveyors<br/>
    <span class="small">Date: {{date_today}}</span>
  </p>
</div>

<div class="footer">
  Generated by NISLA Portal &nbsp;·&nbsp; Surveyor reference {{claim.ref_number}}
</div>

<div class="annex">
  <h2 style="margin-top: 0;">Annexure-A — Itemised Cargo Damage</h2>
  {{loss_items_table}}
  <p class="small" style="margin-top: 14px;">
    All amounts in INR. Quantities reflect the consignor&rsquo;s commercial invoice and
    were verified during the course of survey.
  </p>
</div>

</body>
</html>
$body$,
  'Real-sample-aligned (T-012, T-039)',
  true
)
ON CONFLICT (company, lob, template_name, version) DO NOTHING;

-- Real-sample-aligned (EW-2794)
INSERT INTO public.fsr_lob_templates (company, lob, template_name, version, body_html, notes, is_active)
VALUES (
  'NISLA',
  'Extended Warranty',
  'Production',
  1,
  $body$<!DOCTYPE html>
<!--
  Extended Warranty FSR — NISLA letterhead.

  Source: derived from production sample EW-2794-25-26 in `FSR formats/`
  (Jeep Extended Warranty, Compass MCA, Oriental Insurance).

  Goes into the portal table `fsr_lob_templates` as:
    company='NISLA' lob='Extended Warranty' template_name='Production' version=1

  Customisability: surveyors may clone with template_name='<Plan Name>'
  (e.g. 'Jeep Extended Warranty', 'Toyota True Warranty') for plan-specific
  flavour text or appendices.
-->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Extended Warranty FSR — {{claim.ref_number}}</title>
  <style>
    @page { size: A4; margin: 16mm; }
    body { font-family: 'Times New Roman', Times, serif; font-size: 11pt; color: #111; line-height: 1.45; }

    .letterhead { text-align: center; border-bottom: 2px solid #1e3a5f; padding-bottom: 8px; margin-bottom: 12px; }
    .letterhead h1 { margin: 0; font-size: 13pt; color: #1e3a5f; }
    .letterhead .lob-strip { font-size: 9pt; color: #475569; margin-top: 2px; letter-spacing: 0.4px; }
    .letterhead .sub { font-size: 9pt; color: #475569; margin-top: 2px; }

    .cover { text-align: center; margin: 18px 0 12px; }
    .cover .doc-title { font-size: 16pt; font-weight: 700; color: #1e3a5f; letter-spacing: 0.5px; }
    .cover .ref { font-size: 10pt; margin-top: 6px; color: #475569; }
    .cover .vehicle { font-size: 12pt; font-weight: 700; margin-top: 14px; }
    .cover .vin { font-size: 11pt; margin-top: 4px; }
    .cover .insured { font-size: 11pt; margin-top: 6px; }
    .cover .policy-line { font-size: 10pt; margin-top: 4px; color: #475569; }
    .cover .plan { font-size: 11pt; font-style: italic; margin-top: 10px; color: #1e3a5f; }

    .doc-sub { text-align: center; font-size: 10pt; color: #475569; font-style: italic; margin: 12px 0; }

    .to-block { font-size: 10pt; margin: 12px 0; line-height: 1.45; }
    h2 { font-size: 11pt; color: #1e3a5f; border-bottom: 1px solid #cbd5e1; padding-bottom: 2px; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: 0.3px; }

    table.kv { width: 100%; border-collapse: collapse; margin: 6px 0 12px; }
    table.kv td { padding: 4px 6px; vertical-align: top; border: 1px solid #e2e8f0; font-size: 10pt; }
    table.kv td.lbl { width: 4%; font-weight: 600; color: #475569; text-align: center; }
    table.kv td.k   { width: 28%; font-weight: 600; color: #475569; }

    table.totals { width: 70%; margin: 12px 0 12px auto; border-collapse: collapse; font-size: 11pt; }
    table.totals td { padding: 4px 8px; }
    table.totals tr.grand td { font-weight: 700; border-top: 2px solid #1e3a5f; padding-top: 8px; font-size: 12pt; }
    table.totals td.num { text-align: right; }

    .signoff { margin-top: 30px; padding-top: 12px; border-top: 1px dashed #94a3b8; }
    .footer { margin-top: 24px; font-size: 8pt; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 6px; }
    p { margin: 6px 0; }
    .small { font-size: 9pt; color: #475569; }
    .annex { page-break-before: always; }
  </style>
</head>
<body>

<!-- Cover sheet — page 1 -->
<div class="letterhead">
  <h1>NATHANI INSURANCE SURVEYORS &amp; LOSS ASSESSORS PVT. LTD.</h1>
  <div class="lob-strip">LOP &nbsp;|&nbsp; Fire &nbsp;|&nbsp; Engineering &nbsp;|&nbsp; Misc. &nbsp;|&nbsp; Marine Cargo &nbsp;|&nbsp; Marine Hull</div>
  <div class="sub">IRDA/CORP/S.L.A. No. 200025 (Exp. 03/10/2028)</div>
  <div class="sub">507, Garnet Palladium, Behind Express Zone Bldg., Off WE Highway, Goregaon (E), Mumbai – 400063</div>
</div>

<div class="cover">
  <div class="doc-title">EXTENDED WARRANTY REPORT</div>
  <div class="ref">Ref. No: <strong>{{claim.ref_number}}</strong> &nbsp;·&nbsp; Date: {{date_today}}</div>
  <div class="vehicle">REPORTED LOSS TO VEHICLE NO. {{narrative.registration_no}}</div>
  <div class="vin">VIN NUMBER &mdash; {{narrative.vin}}</div>
  <div class="insured">INSURED: <strong>{{claim.insured_name}}</strong></div>
  <div class="policy-line">{{claim.insurer_name}}</div>
  <div class="policy-line">EXTENDED WARRANTY INSURANCE POLICY NO &mdash; {{claim.policy_number}}</div>
  <div class="plan">{{narrative.plan_name}}</div>
</div>

<!-- Page break -->
<div style="page-break-after: always;"></div>

<!-- Page 2 — addressee + cover paragraph -->
<div class="letterhead">
  <h1>NATHANI INSURANCE SURVEYORS &amp; LOSS ASSESSORS PVT. LTD.</h1>
  <div class="sub">IRDA/CORP/S.L.A. No. 200025 (Exp. 03/10/2028)</div>
</div>

<div class="doc-sub">EXTENDED WARRANTY REPORT (WITHOUT PREJUDICE)</div>

<div class="to-block">
  <strong>To,</strong><br/>
  The Claim In-Charge<br/>
  {{claim.insurer_name}}<br/>
  {{narrative.insurer_office_address}}
</div>

<p><strong>Subject:</strong> Reported claim under Extended Warranty of VIN No. {{narrative.vin}},
   Vehicle No. {{narrative.registration_no}}, Insured: {{claim.insured_name}},
   Policy No: {{claim.policy_number}} || Claim File No: {{claim.claim_number}}</p>

<p>Dear Sir,</p>
<p>Pursuant to valued instruction received from {{narrative.instructions_received_from}} on
   {{claim.date_of_intimation}} for survey and loss assessment of the below mentioned claim,
   we made immediate contact with the insured&rsquo;s representative and conducted the survey
   as per the details below.</p>

<!-- =========================================================== -->
<!-- 1. CLAIM DETAILS                                             -->
<!-- =========================================================== -->
<h2>1. Claim Details</h2>
<p class="small">Now we are submitting our final survey and loss assessment report which is
   based on the following observations and documents provided.</p>
<table class="kv">
  <tr><td class="k">Insured</td><td>{{claim.insured_name}}<br/><span class="small">{{narrative.insured_address}}</span></td></tr>
  <tr><td class="k">Insurer</td><td>{{claim.insurer_name}}<br/><span class="small">{{narrative.insurer_office_address}}</span></td></tr>
  <tr><td class="k">Policy No.</td><td>{{claim.policy_number}}</td></tr>
  <tr><td class="k">Claim File No.</td><td>{{claim.claim_number}}</td></tr>
  <tr><td class="k">Person Contacted</td><td>{{narrative.person_contacted}}</td></tr>
  <tr><td class="k">Estimated Loss Amount</td><td>{{loss_sheet.gross_loss_inr}}</td></tr>
  <tr><td class="k">Claim Type</td><td>Claim under Extended Warranty of VIN No. {{narrative.vin}}</td></tr>
</table>

<!-- =========================================================== -->
<!-- 2. CERTIFICATE / VEHICLE PARTICULARS                          -->
<!-- =========================================================== -->
<h2>2. Certificate / Vehicle Particulars</h2>
<table class="kv">
  <tr><td class="lbl">a</td><td class="k">Name of Customer</td><td>{{narrative.customer_name}}</td></tr>
  <tr><td class="lbl">b</td><td class="k">Registration No.</td><td>{{narrative.registration_no}}</td></tr>
  <tr><td class="lbl">c</td><td class="k">Date of Registration</td><td>{{narrative.date_of_registration}}</td></tr>
  <tr><td class="lbl">d</td><td class="k">Make</td><td>{{narrative.vehicle_make}}</td></tr>
  <tr><td class="lbl">e</td><td class="k">Model / Fuel Type</td><td>{{narrative.vehicle_model}}</td></tr>
  <tr><td class="lbl">f</td><td class="k">Chassis No.</td><td>{{narrative.vin}}</td></tr>
  <tr><td class="lbl">g</td><td class="k">Engine No.</td><td>{{narrative.engine_no}}</td></tr>
  <tr><td class="lbl">h</td><td class="k">Odometer Reading</td><td>{{narrative.odometer}}</td></tr>
  <tr><td class="lbl">i</td><td class="k">Plan</td><td>{{narrative.plan_name}}</td></tr>
  <tr><td class="lbl">j</td><td class="k">Certificate No.</td><td>{{narrative.certificate_no}}</td></tr>
  <tr><td class="lbl">k</td><td class="k">Certificate Validity</td><td>{{narrative.certificate_validity}}</td></tr>
  <tr><td class="lbl">l</td><td class="k">Product</td><td>{{narrative.product_description}}</td></tr>
  <tr><td class="lbl">m</td><td class="k">Terms &amp; Conditions</td><td>{{narrative.terms_and_conditions}}</td></tr>
</table>

<!-- =========================================================== -->
<!-- 3. OUR SURVEY / INSPECTION / FINDINGS                         -->
<!-- =========================================================== -->
<h2>3. Our Survey / Inspection / Findings</h2>
<p>{{narrative.observations}}</p>

<p class="small">Tax Invoice was furnished by the dealer (copy enclosed):</p>
<ul class="small">
  <li>Tax Invoice No: {{narrative.tax_invoice_no}}</li>
  <li>Tax Invoice Date: {{narrative.tax_invoice_date}}</li>
  <li>Invoice Amount: {{narrative.tax_invoice_amount_inr}}</li>
</ul>

<!-- =========================================================== -->
<!-- 4. ASSESSMENT OF LOSS                                         -->
<!-- =========================================================== -->
<h2>4. Assessment of Loss</h2>
<p>We have assessed the loss based on the physical observation of the damages and
   documents / details submitted by the insured.</p>
<p>{{narrative.assessment_basis}}</p>
<p>We have not considered the GST component in our assessment, as the insured would be
   eligible to take GST credit.</p>

<table class="totals">
  <tr><td>Gross Assessed Loss Amount</td><td class="num">{{loss_sheet.gross_loss_inr}}</td></tr>
  <tr><td>Less: GST Amount</td><td class="num">{{loss_sheet.gst_amount_inr}}</td></tr>
  <tr><td>Total</td><td class="num">{{loss_sheet.after_gst_inr}}</td></tr>
  <tr><td>Less: Not Covered</td><td class="num">{{loss_sheet.not_covered_inr}}</td></tr>
  <tr class="grand"><td>Net Adjusted Loss Amount</td><td class="num">{{loss_sheet.net_adjusted_loss_inr}}</td></tr>
</table>

<p>(<strong>{{loss_sheet.net_adjusted_loss_words}}</strong>) subject to policy terms,
   conditions and final approval by the insurer.</p>

<!-- =========================================================== -->
<!-- 5. CONCLUSION                                                 -->
<!-- =========================================================== -->
<h2>5. Conclusion</h2>
<p>In view of the above, as per the Manufacturer Guidelines / Manual, the defective part has
   been replaced with a new one. The same may be considered under extended warranty, subject
   to coverage of the vehicle in the policy and as per the terms and conditions of the policy
   issued.</p>

<p><strong>Note:</strong></p>
<ul class="small">
  <li>Insurers are advised to check the Annexure of the policy and verify if the particular vehicle was declared to the insurer at the time of taking the policy or agreed in the policy.</li>
  <li>Insurers are advised to check the proof of payment (made by the insured to the dealer) before indemnifying the claimed loss.</li>
</ul>

<p>This report is issued without prejudice and is subject to the terms &amp; conditions of
   the policy of insurance issued to and held by the insured, reserving our rights to alter /
   amend unintended error, if any. This concludes our extended warranty report which has been
   issued for perusal of the insurance company.</p>

<p class="small"><em>(For discretion of insurer &amp; their legal advisers only)</em></p>

<div class="signoff">
  <p style="margin-top: 22px;">
    <strong>Authorized Signatory</strong><br/>
    <strong>{{signer.name}}</strong> (Surveyor)<br/>
    IRDAI Licence: {{signer.license}}<br/>
    For Nathani Insurance Surveyors and Loss Assessors Pvt. Ltd.<br/>
    <span class="small">Ref No: {{claim.ref_number}} &nbsp;·&nbsp; Date: {{date_today}}</span>
  </p>
</div>

<div class="footer">
  Generated by NISLA Portal &nbsp;·&nbsp; Surveyor reference {{claim.ref_number}}
</div>

</body>
</html>
$body$,
  'Real-sample-aligned (EW-2794)',
  true
)
ON CONFLICT (company, lob, template_name, version) DO NOTHING;

-- Real-sample-aligned (AS-1752)
INSERT INTO public.fsr_lob_templates (company, lob, template_name, version, body_html, notes, is_active)
VALUES (
  'Acuere',
  'Extended Warranty',
  'Production',
  1,
  $body$<!DOCTYPE html>
<!--
  Extended Warranty FSR — ACUERE letterhead.

  Source: derived from production sample AS-1752-25-26 in `FSR formats/`
  (Toyota True Warranty, Fortuner, Oriental Insurance).

  Goes into the portal table `fsr_lob_templates` as:
    company='Acuere' lob='Extended Warranty' template_name='Production' version=1

  Structurally identical to extended-warranty--nisla.html — only the
  letterhead, IRDAI license, and accent colour differ.
-->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Extended Warranty FSR — {{claim.ref_number}}</title>
  <style>
    @page { size: A4; margin: 16mm; }
    body { font-family: 'Times New Roman', Times, serif; font-size: 11pt; color: #111; line-height: 1.45; }

    .letterhead { text-align: center; border-bottom: 2px solid #1a7ab5; padding-bottom: 8px; margin-bottom: 12px; }
    .letterhead h1 { margin: 0; font-size: 13pt; color: #1a7ab5; }
    .letterhead .lob-strip { font-size: 9pt; color: #475569; margin-top: 2px; letter-spacing: 0.4px; }
    .letterhead .sub { font-size: 9pt; color: #475569; margin-top: 2px; }

    .cover { text-align: center; margin: 18px 0 12px; }
    .cover .doc-title { font-size: 16pt; font-weight: 700; color: #1a7ab5; letter-spacing: 0.5px; }
    .cover .ref { font-size: 10pt; margin-top: 6px; color: #475569; }
    .cover .vehicle { font-size: 12pt; font-weight: 700; margin-top: 14px; }
    .cover .vin { font-size: 11pt; margin-top: 4px; }
    .cover .insured { font-size: 11pt; margin-top: 6px; }
    .cover .policy-line { font-size: 10pt; margin-top: 4px; color: #475569; }
    .cover .plan { font-size: 11pt; font-style: italic; margin-top: 10px; color: #1a7ab5; }

    .doc-sub { text-align: center; font-size: 10pt; color: #475569; font-style: italic; margin: 12px 0; }

    .to-block { font-size: 10pt; margin: 12px 0; line-height: 1.45; }
    h2 { font-size: 11pt; color: #1a7ab5; border-bottom: 1px solid #cbd5e1; padding-bottom: 2px; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: 0.3px; }

    table.kv { width: 100%; border-collapse: collapse; margin: 6px 0 12px; }
    table.kv td { padding: 4px 6px; vertical-align: top; border: 1px solid #e2e8f0; font-size: 10pt; }
    table.kv td.lbl { width: 4%; font-weight: 600; color: #475569; text-align: center; }
    table.kv td.k   { width: 28%; font-weight: 600; color: #475569; }

    table.totals { width: 70%; margin: 12px 0 12px auto; border-collapse: collapse; font-size: 11pt; }
    table.totals td { padding: 4px 8px; }
    table.totals tr.grand td { font-weight: 700; border-top: 2px solid #1a7ab5; padding-top: 8px; font-size: 12pt; }
    table.totals td.num { text-align: right; }

    .signoff { margin-top: 30px; padding-top: 12px; border-top: 1px dashed #94a3b8; }
    .footer { margin-top: 24px; font-size: 8pt; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 6px; }
    p { margin: 6px 0; }
    .small { font-size: 9pt; color: #475569; }
    .annex { page-break-before: always; }
  </style>
</head>
<body>

<div class="letterhead">
  <h1>ACUERE SURVEYORS</h1>
  <div class="lob-strip">Fire &nbsp;|&nbsp; Misc. &nbsp;|&nbsp; Engg. &nbsp;|&nbsp; Marine Cargo &nbsp;|&nbsp; Motor</div>
  <div class="sub">IRDAI Licence: IRDAI/IND/SLA-85225 (Exp. 02/03/2028)</div>
  <div class="sub">A-45, 401, Gurukrupa, Gokuldham, Goregaon (E), Mumbai – 400063</div>
  <div class="sub">Contact: 9892976754, 9892596754 &nbsp;·&nbsp; Email: niteennathani@gmail.com, acueresurveyors@gmail.com</div>
</div>

<div class="cover">
  <div class="doc-title">EXTENDED WARRANTY REPORT</div>
  <div class="ref">Ref. No: <strong>{{claim.ref_number}}</strong> &nbsp;·&nbsp; Date: {{date_today}}</div>
  <div class="vehicle">REPORTED LOSS TO VEHICLE NO. {{narrative.registration_no}}</div>
  <div class="vin">VIN NUMBER &mdash; {{narrative.vin}}</div>
  <div class="insured">INSURED: <strong>{{claim.insured_name}}</strong></div>
  <div class="policy-line">{{claim.insurer_name}}</div>
  <div class="policy-line">EXTENDED WARRANTY INSURANCE POLICY NO &mdash; {{claim.policy_number}}</div>
  <div class="plan">{{narrative.plan_name}}</div>
</div>

<div style="page-break-after: always;"></div>

<div class="letterhead">
  <h1>ACUERE SURVEYORS</h1>
  <div class="sub">IRDAI Licence: IRDAI/IND/SLA-85225 (Exp. 02/03/2028)</div>
</div>

<div class="doc-sub">EXTENDED WARRANTY REPORT (WITHOUT PREJUDICE)</div>

<div class="to-block">
  <strong>To,</strong><br/>
  The Claim In-Charge<br/>
  {{claim.insurer_name}}<br/>
  {{narrative.insurer_office_address}}
</div>

<p><strong>Subject:</strong> Reported claim under Extended Warranty of VIN No. {{narrative.vin}},
   Vehicle No. {{narrative.registration_no}}, Insured: {{claim.insured_name}},
   Policy No: {{claim.policy_number}} || Claim File No: {{claim.claim_number}}</p>

<p>Dear Sir,</p>
<p>Pursuant to valued instruction received from {{narrative.instructions_received_from}} on
   {{claim.date_of_intimation}} for survey and loss assessment of the below mentioned claim,
   we made immediate contact with the insured&rsquo;s representative and conducted the survey
   as per the details below.</p>

<h2>1. Claim Details</h2>
<p class="small">Now we are submitting our final survey and loss assessment report which is
   based on the following observations and documents provided.</p>
<table class="kv">
  <tr><td class="k">Insured</td><td>{{claim.insured_name}}<br/><span class="small">{{narrative.insured_address}}</span></td></tr>
  <tr><td class="k">Insurer</td><td>{{claim.insurer_name}}<br/><span class="small">{{narrative.insurer_office_address}}</span></td></tr>
  <tr><td class="k">Policy No.</td><td>{{claim.policy_number}}</td></tr>
  <tr><td class="k">Claim File No.</td><td>{{claim.claim_number}}</td></tr>
  <tr><td class="k">Person Contacted</td><td>{{narrative.person_contacted}}</td></tr>
  <tr><td class="k">Estimated Loss Amount</td><td>{{loss_sheet.gross_loss_inr}}</td></tr>
  <tr><td class="k">Claim Type</td><td>Claim under Extended Warranty of VIN No. {{narrative.vin}}</td></tr>
</table>

<h2>2. Certificate / Vehicle Particulars</h2>
<table class="kv">
  <tr><td class="lbl">a</td><td class="k">Name of Customer</td><td>{{narrative.customer_name}}</td></tr>
  <tr><td class="lbl">b</td><td class="k">Registration No.</td><td>{{narrative.registration_no}}</td></tr>
  <tr><td class="lbl">c</td><td class="k">Date of Registration</td><td>{{narrative.date_of_registration}}</td></tr>
  <tr><td class="lbl">d</td><td class="k">Make</td><td>{{narrative.vehicle_make}}</td></tr>
  <tr><td class="lbl">e</td><td class="k">Model / Fuel Type</td><td>{{narrative.vehicle_model}}</td></tr>
  <tr><td class="lbl">f</td><td class="k">Chassis No.</td><td>{{narrative.vin}}</td></tr>
  <tr><td class="lbl">g</td><td class="k">Engine No.</td><td>{{narrative.engine_no}}</td></tr>
  <tr><td class="lbl">h</td><td class="k">Odometer Reading</td><td>{{narrative.odometer}}</td></tr>
  <tr><td class="lbl">i</td><td class="k">Plan</td><td>{{narrative.plan_name}}</td></tr>
  <tr><td class="lbl">j</td><td class="k">Certificate No.</td><td>{{narrative.certificate_no}}</td></tr>
  <tr><td class="lbl">k</td><td class="k">Certificate Validity</td><td>{{narrative.certificate_validity}}</td></tr>
  <tr><td class="lbl">l</td><td class="k">Product</td><td>{{narrative.product_description}}</td></tr>
  <tr><td class="lbl">m</td><td class="k">Terms &amp; Conditions</td><td>{{narrative.terms_and_conditions}}</td></tr>
</table>

<h2>3. Our Survey / Inspection / Findings</h2>
<p>{{narrative.observations}}</p>

<p class="small">Tax Invoice was furnished by the dealer (copy enclosed):</p>
<ul class="small">
  <li>Tax Invoice No: {{narrative.tax_invoice_no}}</li>
  <li>Tax Invoice Date: {{narrative.tax_invoice_date}}</li>
  <li>Invoice Amount: {{narrative.tax_invoice_amount_inr}}</li>
</ul>

<h2>4. Assessment of Loss</h2>
<p>We have assessed the loss based on the physical observation of the damages and
   documents / details submitted by the insured.</p>
<p>{{narrative.assessment_basis}}</p>
<p>We have not considered the GST component in our assessment, as the insured would be
   eligible to take GST credit.</p>

<table class="totals">
  <tr><td>Gross Assessed Loss Amount</td><td class="num">{{loss_sheet.gross_loss_inr}}</td></tr>
  <tr><td>Less: GST Amount</td><td class="num">{{loss_sheet.gst_amount_inr}}</td></tr>
  <tr><td>Total</td><td class="num">{{loss_sheet.after_gst_inr}}</td></tr>
  <tr><td>Less: Not Covered</td><td class="num">{{loss_sheet.not_covered_inr}}</td></tr>
  <tr class="grand"><td>Net Adjusted Loss Amount</td><td class="num">{{loss_sheet.net_adjusted_loss_inr}}</td></tr>
</table>

<p>(<strong>{{loss_sheet.net_adjusted_loss_words}}</strong>) subject to policy terms,
   conditions and final approval by the insurer.</p>

<h2>5. Conclusion</h2>
<p>In view of the above, as per the Manufacturer Guidelines / Manual, the defective part has
   been replaced with a new one. The same may be considered under extended warranty, subject
   to coverage of the vehicle in the policy and as per the terms and conditions of the policy
   issued.</p>

<p><strong>Note:</strong></p>
<ul class="small">
  <li>Insurers are advised to check the Annexure of the policy and verify if the particular vehicle was declared to the insurer at the time of taking the policy or agreed in the policy.</li>
  <li>Insurers are advised to check the proof of payment (made by the insured to the dealer) before indemnifying the claimed loss.</li>
</ul>

<p>This report is issued without prejudice and is subject to the terms &amp; conditions of
   the policy of insurance issued to and held by the insured, reserving our rights to alter /
   amend unintended error, if any. This concludes our extended warranty report which has been
   issued for perusal of the insurance company.</p>

<p class="small"><em>(For discretion of insurer &amp; their legal advisers only)</em></p>

<div class="signoff">
  <p style="margin-top: 22px;">
    <strong>Authorized Signatory</strong><br/>
    <strong>{{signer.name}}</strong> (Surveyor)<br/>
    IRDAI Licence: {{signer.license}}<br/>
    For Acuere Surveyors<br/>
    <span class="small">Ref No: {{claim.ref_number}} &nbsp;·&nbsp; Date: {{date_today}}</span>
  </p>
</div>

<div class="footer">
  Generated by NISLA Portal &nbsp;·&nbsp; Surveyor reference {{claim.ref_number}}
</div>

</body>
</html>
$body$,
  'Real-sample-aligned (AS-1752)',
  true
)
ON CONFLICT (company, lob, template_name, version) DO NOTHING;

-- Initial Loss Advice — 72-hour preliminary
INSERT INTO public.fsr_lob_templates (company, lob, template_name, version, body_html, notes, is_active)
VALUES (
  'NISLA',
  'Marine Cargo',
  'ILA',
  1,
  $body$<!DOCTYPE html>
<!--
  Initial Loss Advice (ILA) — Marine Cargo. Firm-agnostic skeleton; the
  letterhead block at top reads from {{company.*}} so the same template
  works for both NISLA and Acuere.

  The ILA is the 72-hour preliminary report issued before the full
  survey is complete (per IRDAI Surveyors Regs 2015 — see
  CLAUDE.md §13). It captures: cause-of-loss preliminary view,
  estimated reserve, immediate observations, list of documents
  pending. It does NOT recommend a settlement amount.

  Goes into the portal table `fsr_lob_templates` as:
    company=<NISLA|Acuere> lob='Marine Cargo' template_name='ILA' version=1

  (Same lob as the full FSR, just a different template_name.)
-->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>ILA — Marine Cargo — {{claim.ref_number}}</title>
  <style>
    @page { size: A4; margin: 16mm; }
    body { font-family: 'Times New Roman', Times, serif; font-size: 11pt; color: #111; line-height: 1.45; }

    .letterhead { text-align: center; border-bottom: 2px solid {{company.accent_color}}; padding-bottom: 8px; margin-bottom: 12px; }
    .letterhead h1 { margin: 0; font-size: 14pt; color: {{company.accent_color}}; }
    .letterhead .sub { font-size: 9pt; color: #475569; margin-top: 2px; }

    .ref-line { display: flex; justify-content: space-between; font-size: 10pt; margin: 8px 0; }
    .doc-title { text-align: center; font-size: 13pt; font-weight: 700; margin: 14px 0 4px; color: {{company.accent_color}}; letter-spacing: 0.4px; }
    .doc-sub { text-align: center; font-size: 10pt; color: #475569; font-style: italic; margin-bottom: 12px; }

    h2 { font-size: 11pt; color: {{company.accent_color}}; border-bottom: 1px solid #cbd5e1; padding-bottom: 2px; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: 0.3px; }

    table.kv { width: 100%; border-collapse: collapse; margin: 6px 0 12px; }
    table.kv td { padding: 4px 6px; vertical-align: top; border: 1px solid #e2e8f0; font-size: 10pt; }
    table.kv td.k { width: 30%; font-weight: 600; color: #475569; }

    .signoff { margin-top: 30px; padding-top: 12px; border-top: 1px dashed #94a3b8; }
    .footer { margin-top: 24px; font-size: 8pt; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 6px; }
    p { margin: 6px 0; }
    .small { font-size: 9pt; color: #475569; }
    .reserve { font-size: 13pt; font-weight: 700; color: {{company.accent_color}}; padding: 6px 0; }
  </style>
</head>
<body>

<div class="letterhead">
  <h1>{{company.name}}</h1>
  <div class="sub">{{company.license_line}}</div>
  <div class="sub">{{company.address_line}}</div>
</div>

<div class="ref-line">
  <span><strong>Ref. No:</strong> {{claim.ref_number}}</span>
  <span><strong>Date:</strong> {{date_today}}</span>
</div>

<div class="doc-title">INITIAL LOSS ADVICE (ILA) &mdash; MARINE CARGO</div>
<div class="doc-sub">(WITHOUT PREJUDICE)</div>

<p><strong>To,</strong><br/>
   The Manager,<br/>
   {{claim.insurer_name}}<br/>
   {{narrative.insurer_office_address}}</p>

<p><strong>Subject:</strong> Preliminary loss advice — Marine Cargo claim<br/>
   <span class="small">Policy No: {{claim.policy_number}} || Insured: {{claim.insured_name}} || Claim No: {{claim.claim_number}} || LR No: {{narrative.lr_no}}</span></p>

<p>Dear Sir,</p>
<p>Pursuant to your instructions received on {{claim.date_of_intimation}}, we have made
   immediate contact with the insured&rsquo;s representative and visited the loss site /
   warehouse for a preliminary inspection. This Initial Loss Advice records our
   first-look findings; a full Final Survey Report will follow once documentation and
   formal assessment are complete.</p>

<h2>1. Claim Summary</h2>
<table class="kv">
  <tr><td class="k">Insurer</td><td>{{claim.insurer_name}}</td></tr>
  <tr><td class="k">Insured</td><td>{{claim.insured_name}}</td></tr>
  <tr><td class="k">Policy No.</td><td>{{claim.policy_number}}</td></tr>
  <tr><td class="k">Type of Policy</td><td>{{claim.lob_subcategory}}</td></tr>
  <tr><td class="k">Sum Insured</td><td>{{loss_sheet.sum_insured_inr}}</td></tr>
  <tr><td class="k">Date of Loss</td><td>{{claim.date_loss}}</td></tr>
  <tr><td class="k">Date of Intimation</td><td>{{claim.date_of_intimation}}</td></tr>
  <tr><td class="k">Loss Location / Transit</td><td>{{narrative.transit}}</td></tr>
  <tr><td class="k">LR / Consignment</td><td>{{narrative.lr_no}} dated {{narrative.lr_date}}</td></tr>
  <tr><td class="k">Carrier</td><td>{{narrative.carrier}}</td></tr>
</table>

<h2>2. Preliminary Findings</h2>
<p>{{narrative.preliminary_findings}}</p>

<h2>3. Cause of Loss (Preliminary View)</h2>
<p>{{ila.preliminary_view}}</p>

<h2>4. Coverage Position (Preliminary)</h2>
<p>Subject to confirmation against the full policy schedule and final documentation,
   the loss <strong>{{ila.preliminary_admissibility_label}}</strong> appears to fall
   within the cover provided. {{ila.admissibility_reasoning}}</p>

<h2>5. Estimated Loss Reserve</h2>
<p>Based on the inspection and the documents seen so far, we recommend the insurer
   reserve approximately:</p>
<p class="reserve">{{loss_sheet.estimated_reserve_inr}}</p>
<p class="small">This is a preliminary, indicative figure only. The Net Adjusted Loss
   will be determined in the Final Survey Report after full documentation is reviewed
   and item-wise assessment is completed.</p>

<h2>6. Documents Pending from Insured</h2>
<p>{{narrative.documents_pending}}</p>

<h2>7. Next Steps</h2>
<p>{{narrative.next_steps}}</p>

<div class="signoff">
  <p style="margin-top: 22px;">
    <strong>Authorized Signatory</strong><br/>
    <strong>{{signer.name}}</strong> (Surveyor)<br/>
    IRDAI Licence: {{signer.license}}<br/>
    For {{company.name}}<br/>
    <span class="small">Date: {{date_today}}</span>
  </p>
</div>

<p class="small"><em>This Initial Loss Advice is issued without prejudice and is subject
   to the terms and conditions of the policy of insurance. The figures above are
   indicative; final assessment will be communicated via the Final Survey Report.</em></p>

<div class="footer">
  Generated by NISLA Portal &nbsp;·&nbsp; Surveyor reference {{claim.ref_number}}
</div>

</body>
</html>
$body$,
  'Initial Loss Advice — 72-hour preliminary',
  true
)
ON CONFLICT (company, lob, template_name, version) DO NOTHING;

-- Initial Loss Advice — 72-hour preliminary
INSERT INTO public.fsr_lob_templates (company, lob, template_name, version, body_html, notes, is_active)
VALUES (
  'Acuere',
  'Marine Cargo',
  'ILA',
  1,
  $body$<!DOCTYPE html>
<!--
  Initial Loss Advice (ILA) — Marine Cargo. Firm-agnostic skeleton; the
  letterhead block at top reads from {{company.*}} so the same template
  works for both NISLA and Acuere.

  The ILA is the 72-hour preliminary report issued before the full
  survey is complete (per IRDAI Surveyors Regs 2015 — see
  CLAUDE.md §13). It captures: cause-of-loss preliminary view,
  estimated reserve, immediate observations, list of documents
  pending. It does NOT recommend a settlement amount.

  Goes into the portal table `fsr_lob_templates` as:
    company=<NISLA|Acuere> lob='Marine Cargo' template_name='ILA' version=1

  (Same lob as the full FSR, just a different template_name.)
-->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>ILA — Marine Cargo — {{claim.ref_number}}</title>
  <style>
    @page { size: A4; margin: 16mm; }
    body { font-family: 'Times New Roman', Times, serif; font-size: 11pt; color: #111; line-height: 1.45; }

    .letterhead { text-align: center; border-bottom: 2px solid {{company.accent_color}}; padding-bottom: 8px; margin-bottom: 12px; }
    .letterhead h1 { margin: 0; font-size: 14pt; color: {{company.accent_color}}; }
    .letterhead .sub { font-size: 9pt; color: #475569; margin-top: 2px; }

    .ref-line { display: flex; justify-content: space-between; font-size: 10pt; margin: 8px 0; }
    .doc-title { text-align: center; font-size: 13pt; font-weight: 700; margin: 14px 0 4px; color: {{company.accent_color}}; letter-spacing: 0.4px; }
    .doc-sub { text-align: center; font-size: 10pt; color: #475569; font-style: italic; margin-bottom: 12px; }

    h2 { font-size: 11pt; color: {{company.accent_color}}; border-bottom: 1px solid #cbd5e1; padding-bottom: 2px; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: 0.3px; }

    table.kv { width: 100%; border-collapse: collapse; margin: 6px 0 12px; }
    table.kv td { padding: 4px 6px; vertical-align: top; border: 1px solid #e2e8f0; font-size: 10pt; }
    table.kv td.k { width: 30%; font-weight: 600; color: #475569; }

    .signoff { margin-top: 30px; padding-top: 12px; border-top: 1px dashed #94a3b8; }
    .footer { margin-top: 24px; font-size: 8pt; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 6px; }
    p { margin: 6px 0; }
    .small { font-size: 9pt; color: #475569; }
    .reserve { font-size: 13pt; font-weight: 700; color: {{company.accent_color}}; padding: 6px 0; }
  </style>
</head>
<body>

<div class="letterhead">
  <h1>{{company.name}}</h1>
  <div class="sub">{{company.license_line}}</div>
  <div class="sub">{{company.address_line}}</div>
</div>

<div class="ref-line">
  <span><strong>Ref. No:</strong> {{claim.ref_number}}</span>
  <span><strong>Date:</strong> {{date_today}}</span>
</div>

<div class="doc-title">INITIAL LOSS ADVICE (ILA) &mdash; MARINE CARGO</div>
<div class="doc-sub">(WITHOUT PREJUDICE)</div>

<p><strong>To,</strong><br/>
   The Manager,<br/>
   {{claim.insurer_name}}<br/>
   {{narrative.insurer_office_address}}</p>

<p><strong>Subject:</strong> Preliminary loss advice — Marine Cargo claim<br/>
   <span class="small">Policy No: {{claim.policy_number}} || Insured: {{claim.insured_name}} || Claim No: {{claim.claim_number}} || LR No: {{narrative.lr_no}}</span></p>

<p>Dear Sir,</p>
<p>Pursuant to your instructions received on {{claim.date_of_intimation}}, we have made
   immediate contact with the insured&rsquo;s representative and visited the loss site /
   warehouse for a preliminary inspection. This Initial Loss Advice records our
   first-look findings; a full Final Survey Report will follow once documentation and
   formal assessment are complete.</p>

<h2>1. Claim Summary</h2>
<table class="kv">
  <tr><td class="k">Insurer</td><td>{{claim.insurer_name}}</td></tr>
  <tr><td class="k">Insured</td><td>{{claim.insured_name}}</td></tr>
  <tr><td class="k">Policy No.</td><td>{{claim.policy_number}}</td></tr>
  <tr><td class="k">Type of Policy</td><td>{{claim.lob_subcategory}}</td></tr>
  <tr><td class="k">Sum Insured</td><td>{{loss_sheet.sum_insured_inr}}</td></tr>
  <tr><td class="k">Date of Loss</td><td>{{claim.date_loss}}</td></tr>
  <tr><td class="k">Date of Intimation</td><td>{{claim.date_of_intimation}}</td></tr>
  <tr><td class="k">Loss Location / Transit</td><td>{{narrative.transit}}</td></tr>
  <tr><td class="k">LR / Consignment</td><td>{{narrative.lr_no}} dated {{narrative.lr_date}}</td></tr>
  <tr><td class="k">Carrier</td><td>{{narrative.carrier}}</td></tr>
</table>

<h2>2. Preliminary Findings</h2>
<p>{{narrative.preliminary_findings}}</p>

<h2>3. Cause of Loss (Preliminary View)</h2>
<p>{{ila.preliminary_view}}</p>

<h2>4. Coverage Position (Preliminary)</h2>
<p>Subject to confirmation against the full policy schedule and final documentation,
   the loss <strong>{{ila.preliminary_admissibility_label}}</strong> appears to fall
   within the cover provided. {{ila.admissibility_reasoning}}</p>

<h2>5. Estimated Loss Reserve</h2>
<p>Based on the inspection and the documents seen so far, we recommend the insurer
   reserve approximately:</p>
<p class="reserve">{{loss_sheet.estimated_reserve_inr}}</p>
<p class="small">This is a preliminary, indicative figure only. The Net Adjusted Loss
   will be determined in the Final Survey Report after full documentation is reviewed
   and item-wise assessment is completed.</p>

<h2>6. Documents Pending from Insured</h2>
<p>{{narrative.documents_pending}}</p>

<h2>7. Next Steps</h2>
<p>{{narrative.next_steps}}</p>

<div class="signoff">
  <p style="margin-top: 22px;">
    <strong>Authorized Signatory</strong><br/>
    <strong>{{signer.name}}</strong> (Surveyor)<br/>
    IRDAI Licence: {{signer.license}}<br/>
    For {{company.name}}<br/>
    <span class="small">Date: {{date_today}}</span>
  </p>
</div>

<p class="small"><em>This Initial Loss Advice is issued without prejudice and is subject
   to the terms and conditions of the policy of insurance. The figures above are
   indicative; final assessment will be communicated via the Final Survey Report.</em></p>

<div class="footer">
  Generated by NISLA Portal &nbsp;·&nbsp; Surveyor reference {{claim.ref_number}}
</div>

</body>
</html>
$body$,
  'Initial Loss Advice — 72-hour preliminary',
  true
)
ON CONFLICT (company, lob, template_name, version) DO NOTHING;

-- Initial Loss Advice — 72-hour preliminary
INSERT INTO public.fsr_lob_templates (company, lob, template_name, version, body_html, notes, is_active)
VALUES (
  'NISLA',
  'Extended Warranty',
  'ILA',
  1,
  $body$<!DOCTYPE html>
<!--
  Initial Loss Advice (ILA) — Extended Warranty. Firm-agnostic skeleton.
  See ila-marine-cargo.html header notes; the same structure applies.

  Goes into the portal table `fsr_lob_templates` as:
    company=<NISLA|Acuere> lob='Extended Warranty' template_name='ILA' version=1
-->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>ILA — Extended Warranty — {{claim.ref_number}}</title>
  <style>
    @page { size: A4; margin: 16mm; }
    body { font-family: 'Times New Roman', Times, serif; font-size: 11pt; color: #111; line-height: 1.45; }

    .letterhead { text-align: center; border-bottom: 2px solid {{company.accent_color}}; padding-bottom: 8px; margin-bottom: 12px; }
    .letterhead h1 { margin: 0; font-size: 14pt; color: {{company.accent_color}}; }
    .letterhead .sub { font-size: 9pt; color: #475569; margin-top: 2px; }

    .ref-line { display: flex; justify-content: space-between; font-size: 10pt; margin: 8px 0; }
    .doc-title { text-align: center; font-size: 13pt; font-weight: 700; margin: 14px 0 4px; color: {{company.accent_color}}; letter-spacing: 0.4px; }
    .doc-sub { text-align: center; font-size: 10pt; color: #475569; font-style: italic; margin-bottom: 12px; }

    h2 { font-size: 11pt; color: {{company.accent_color}}; border-bottom: 1px solid #cbd5e1; padding-bottom: 2px; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: 0.3px; }

    table.kv { width: 100%; border-collapse: collapse; margin: 6px 0 12px; }
    table.kv td { padding: 4px 6px; vertical-align: top; border: 1px solid #e2e8f0; font-size: 10pt; }
    table.kv td.k { width: 30%; font-weight: 600; color: #475569; }

    .signoff { margin-top: 30px; padding-top: 12px; border-top: 1px dashed #94a3b8; }
    .footer { margin-top: 24px; font-size: 8pt; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 6px; }
    p { margin: 6px 0; }
    .small { font-size: 9pt; color: #475569; }
    .reserve { font-size: 13pt; font-weight: 700; color: {{company.accent_color}}; padding: 6px 0; }
  </style>
</head>
<body>

<div class="letterhead">
  <h1>{{company.name}}</h1>
  <div class="sub">{{company.license_line}}</div>
  <div class="sub">{{company.address_line}}</div>
</div>

<div class="ref-line">
  <span><strong>Ref. No:</strong> {{claim.ref_number}}</span>
  <span><strong>Date:</strong> {{date_today}}</span>
</div>

<div class="doc-title">INITIAL LOSS ADVICE (ILA) &mdash; EXTENDED WARRANTY</div>
<div class="doc-sub">(WITHOUT PREJUDICE)</div>

<p><strong>To,</strong><br/>
   The Claim In-Charge<br/>
   {{claim.insurer_name}}<br/>
   {{narrative.insurer_office_address}}</p>

<p><strong>Subject:</strong> Preliminary loss advice — Extended Warranty claim<br/>
   <span class="small">Vehicle No: {{narrative.registration_no}} || VIN: {{narrative.vin}} || Policy No: {{claim.policy_number}} || Claim File No: {{claim.claim_number}}</span></p>

<p>Dear Sir,</p>
<p>Pursuant to your instructions received on {{claim.date_of_intimation}} we made
   immediate contact with the dealer / service centre and conducted a preliminary
   inspection of the affected vehicle. This Initial Loss Advice records our first-look
   findings; a full Final Survey Report will follow once the dealer completes diagnosis
   and produces the tax invoice for the repair.</p>

<h2>1. Claim Summary</h2>
<table class="kv">
  <tr><td class="k">Insurer</td><td>{{claim.insurer_name}}</td></tr>
  <tr><td class="k">Insured</td><td>{{claim.insured_name}}</td></tr>
  <tr><td class="k">Policy No.</td><td>{{claim.policy_number}}</td></tr>
  <tr><td class="k">Plan</td><td>{{narrative.plan_name}}</td></tr>
  <tr><td class="k">Customer Name</td><td>{{narrative.customer_name}}</td></tr>
  <tr><td class="k">Vehicle / Reg No.</td><td>{{narrative.vehicle_make}} {{narrative.vehicle_model}} ({{narrative.registration_no}})</td></tr>
  <tr><td class="k">VIN / Chassis</td><td>{{narrative.vin}}</td></tr>
  <tr><td class="k">Odometer Reading</td><td>{{narrative.odometer}}</td></tr>
  <tr><td class="k">Date of Loss</td><td>{{claim.date_loss}}</td></tr>
  <tr><td class="k">Service Centre</td><td>{{narrative.service_centre}}</td></tr>
</table>

<h2>2. Customer Complaint</h2>
<p>{{narrative.customer_complaint}}</p>

<h2>3. Preliminary Findings</h2>
<p>{{narrative.preliminary_findings}}</p>

<h2>4. Coverage Position (Preliminary)</h2>
<p>Subject to confirmation against the policy annexure (vehicle declaration) and final
   review of the dealer&rsquo;s diagnosis, the affected components
   <strong>{{ila.preliminary_admissibility_label}}</strong> appear to fall within the
   cover provided under {{narrative.plan_name}}.</p>
<p>{{ila.admissibility_reasoning}}</p>

<h2>5. Estimated Loss Reserve</h2>
<p>Based on the dealer&rsquo;s preliminary diagnosis we recommend the insurer reserve
   approximately:</p>
<p class="reserve">{{loss_sheet.estimated_reserve_inr}}</p>
<p class="small">This is a preliminary, indicative figure only. The Net Adjusted Loss
   will be determined in the Final Survey Report after the dealer issues the tax
   invoice and we have re-inspected the repaired vehicle and the removed parts.</p>

<h2>6. Documents Pending</h2>
<p>{{narrative.documents_pending}}</p>

<h2>7. Next Steps</h2>
<p>{{narrative.next_steps}}</p>

<div class="signoff">
  <p style="margin-top: 22px;">
    <strong>Authorized Signatory</strong><br/>
    <strong>{{signer.name}}</strong> (Surveyor)<br/>
    IRDAI Licence: {{signer.license}}<br/>
    For {{company.name}}<br/>
    <span class="small">Date: {{date_today}}</span>
  </p>
</div>

<p class="small"><em>This Initial Loss Advice is issued without prejudice and is subject
   to the terms and conditions of the policy of insurance. The figures above are
   indicative; final assessment will be communicated via the Final Survey Report.</em></p>

<div class="footer">
  Generated by NISLA Portal &nbsp;·&nbsp; Surveyor reference {{claim.ref_number}}
</div>

</body>
</html>
$body$,
  'Initial Loss Advice — 72-hour preliminary',
  true
)
ON CONFLICT (company, lob, template_name, version) DO NOTHING;

-- Initial Loss Advice — 72-hour preliminary
INSERT INTO public.fsr_lob_templates (company, lob, template_name, version, body_html, notes, is_active)
VALUES (
  'Acuere',
  'Extended Warranty',
  'ILA',
  1,
  $body$<!DOCTYPE html>
<!--
  Initial Loss Advice (ILA) — Extended Warranty. Firm-agnostic skeleton.
  See ila-marine-cargo.html header notes; the same structure applies.

  Goes into the portal table `fsr_lob_templates` as:
    company=<NISLA|Acuere> lob='Extended Warranty' template_name='ILA' version=1
-->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>ILA — Extended Warranty — {{claim.ref_number}}</title>
  <style>
    @page { size: A4; margin: 16mm; }
    body { font-family: 'Times New Roman', Times, serif; font-size: 11pt; color: #111; line-height: 1.45; }

    .letterhead { text-align: center; border-bottom: 2px solid {{company.accent_color}}; padding-bottom: 8px; margin-bottom: 12px; }
    .letterhead h1 { margin: 0; font-size: 14pt; color: {{company.accent_color}}; }
    .letterhead .sub { font-size: 9pt; color: #475569; margin-top: 2px; }

    .ref-line { display: flex; justify-content: space-between; font-size: 10pt; margin: 8px 0; }
    .doc-title { text-align: center; font-size: 13pt; font-weight: 700; margin: 14px 0 4px; color: {{company.accent_color}}; letter-spacing: 0.4px; }
    .doc-sub { text-align: center; font-size: 10pt; color: #475569; font-style: italic; margin-bottom: 12px; }

    h2 { font-size: 11pt; color: {{company.accent_color}}; border-bottom: 1px solid #cbd5e1; padding-bottom: 2px; margin: 14px 0 6px; text-transform: uppercase; letter-spacing: 0.3px; }

    table.kv { width: 100%; border-collapse: collapse; margin: 6px 0 12px; }
    table.kv td { padding: 4px 6px; vertical-align: top; border: 1px solid #e2e8f0; font-size: 10pt; }
    table.kv td.k { width: 30%; font-weight: 600; color: #475569; }

    .signoff { margin-top: 30px; padding-top: 12px; border-top: 1px dashed #94a3b8; }
    .footer { margin-top: 24px; font-size: 8pt; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 6px; }
    p { margin: 6px 0; }
    .small { font-size: 9pt; color: #475569; }
    .reserve { font-size: 13pt; font-weight: 700; color: {{company.accent_color}}; padding: 6px 0; }
  </style>
</head>
<body>

<div class="letterhead">
  <h1>{{company.name}}</h1>
  <div class="sub">{{company.license_line}}</div>
  <div class="sub">{{company.address_line}}</div>
</div>

<div class="ref-line">
  <span><strong>Ref. No:</strong> {{claim.ref_number}}</span>
  <span><strong>Date:</strong> {{date_today}}</span>
</div>

<div class="doc-title">INITIAL LOSS ADVICE (ILA) &mdash; EXTENDED WARRANTY</div>
<div class="doc-sub">(WITHOUT PREJUDICE)</div>

<p><strong>To,</strong><br/>
   The Claim In-Charge<br/>
   {{claim.insurer_name}}<br/>
   {{narrative.insurer_office_address}}</p>

<p><strong>Subject:</strong> Preliminary loss advice — Extended Warranty claim<br/>
   <span class="small">Vehicle No: {{narrative.registration_no}} || VIN: {{narrative.vin}} || Policy No: {{claim.policy_number}} || Claim File No: {{claim.claim_number}}</span></p>

<p>Dear Sir,</p>
<p>Pursuant to your instructions received on {{claim.date_of_intimation}} we made
   immediate contact with the dealer / service centre and conducted a preliminary
   inspection of the affected vehicle. This Initial Loss Advice records our first-look
   findings; a full Final Survey Report will follow once the dealer completes diagnosis
   and produces the tax invoice for the repair.</p>

<h2>1. Claim Summary</h2>
<table class="kv">
  <tr><td class="k">Insurer</td><td>{{claim.insurer_name}}</td></tr>
  <tr><td class="k">Insured</td><td>{{claim.insured_name}}</td></tr>
  <tr><td class="k">Policy No.</td><td>{{claim.policy_number}}</td></tr>
  <tr><td class="k">Plan</td><td>{{narrative.plan_name}}</td></tr>
  <tr><td class="k">Customer Name</td><td>{{narrative.customer_name}}</td></tr>
  <tr><td class="k">Vehicle / Reg No.</td><td>{{narrative.vehicle_make}} {{narrative.vehicle_model}} ({{narrative.registration_no}})</td></tr>
  <tr><td class="k">VIN / Chassis</td><td>{{narrative.vin}}</td></tr>
  <tr><td class="k">Odometer Reading</td><td>{{narrative.odometer}}</td></tr>
  <tr><td class="k">Date of Loss</td><td>{{claim.date_loss}}</td></tr>
  <tr><td class="k">Service Centre</td><td>{{narrative.service_centre}}</td></tr>
</table>

<h2>2. Customer Complaint</h2>
<p>{{narrative.customer_complaint}}</p>

<h2>3. Preliminary Findings</h2>
<p>{{narrative.preliminary_findings}}</p>

<h2>4. Coverage Position (Preliminary)</h2>
<p>Subject to confirmation against the policy annexure (vehicle declaration) and final
   review of the dealer&rsquo;s diagnosis, the affected components
   <strong>{{ila.preliminary_admissibility_label}}</strong> appear to fall within the
   cover provided under {{narrative.plan_name}}.</p>
<p>{{ila.admissibility_reasoning}}</p>

<h2>5. Estimated Loss Reserve</h2>
<p>Based on the dealer&rsquo;s preliminary diagnosis we recommend the insurer reserve
   approximately:</p>
<p class="reserve">{{loss_sheet.estimated_reserve_inr}}</p>
<p class="small">This is a preliminary, indicative figure only. The Net Adjusted Loss
   will be determined in the Final Survey Report after the dealer issues the tax
   invoice and we have re-inspected the repaired vehicle and the removed parts.</p>

<h2>6. Documents Pending</h2>
<p>{{narrative.documents_pending}}</p>

<h2>7. Next Steps</h2>
<p>{{narrative.next_steps}}</p>

<div class="signoff">
  <p style="margin-top: 22px;">
    <strong>Authorized Signatory</strong><br/>
    <strong>{{signer.name}}</strong> (Surveyor)<br/>
    IRDAI Licence: {{signer.license}}<br/>
    For {{company.name}}<br/>
    <span class="small">Date: {{date_today}}</span>
  </p>
</div>

<p class="small"><em>This Initial Loss Advice is issued without prejudice and is subject
   to the terms and conditions of the policy of insurance. The figures above are
   indicative; final assessment will be communicated via the Final Survey Report.</em></p>

<div class="footer">
  Generated by NISLA Portal &nbsp;·&nbsp; Surveyor reference {{claim.ref_number}}
</div>

</body>
</html>
$body$,
  'Initial Loss Advice — 72-hour preliminary',
  true
)
ON CONFLICT (company, lob, template_name, version) DO NOTHING;

-- -----------------------------------------------------------------------------
-- Optional: deactivate the old 'Default' templates so 'Production' wins.
-- Run only after verifying that the new templates render correctly with
-- production data. Leave commented out otherwise.
-- -----------------------------------------------------------------------------
--
-- UPDATE public.fsr_lob_templates
--    SET is_active = false, updated_at = NOW()
--  WHERE template_name = 'Default'
--    AND lob IN ('Marine Cargo', 'Extended Warranty')
--    AND is_active = true;
